// Generated by insterra

module "aws_compute_deneb_nuw" {
  source  = "upmaru/instellar/aws"
  version = "0.7.6"

  bastion_size = "t3a.micro"
  cluster_topology = [
  ]

  identifier           = "deneb-nuw"
  network_dependencies = module.aws_networking_deneb_fki.dependencies
  node_size            = "c5a.large"
  public_subnet_ids    = module.aws_networking_deneb_fki.public_subnet_ids
  ssh_keys             = ["zack-studio", "zack-mbp"]
  storage_size         = 40
  volume_type          = "gp3"
  vpc_id               = module.aws_networking_deneb_fki.vpc_id
  vpc_ip_range         = module.aws_networking_deneb_fki.vpc_ip_range
}
