// Generated by insterra

module "instellar_link_deneb_gsm" {
  source  = "upmaru/bootstrap/instellar"
  version = "0.6.3"

  bootstrap_node        = module.aws_compute_deneb_nuw.bootstrap_node
  cluster_address       = module.aws_compute_deneb_nuw.cluster_address
  cluster_name          = module.aws_compute_deneb_nuw.identifier
  insterra_component_id = 200
  kit_slug              = "lite"
  nodes                 = module.aws_compute_deneb_nuw.nodes
  password_token        = module.aws_compute_deneb_nuw.trust_token
  provider_name         = "aws"
  region                = var.aws_region

}

module "instellar_link_deneb_zef" {
  source  = "upmaru/bootstrap/instellar//modules/service"
  version = "0.6.3"


  channels = ["main", "master"]
  cluster_ids = [
    module.instellar_link_deneb_gsm.cluster_id
  ]
  credential = {
    host     = module.aws_bucket_deneb_ecp.host
    password = module.aws_bucket_deneb_ecp.secret_access_key
    port     = module.aws_bucket_deneb_ecp.port
    resource = module.aws_bucket_deneb_ecp.region
    username = module.aws_bucket_deneb_ecp.access_key_id
    secure   = true
  }

  driver                = "bucket/aws-s3"
  driver_version        = module.aws_bucket_deneb_ecp.version
  insterra_component_id = 202
  provider_name         = "aws"
  slug                  = module.aws_bucket_deneb_ecp.identifier
}

module "instellar_link_deneb_swp" {
  source  = "upmaru/bootstrap/instellar//modules/service"
  version = "0.6.3"

  certificate = module.aws_database_deneb_ayk.certificate_url
  channels    = ["main", "master"]
  cluster_ids = [
    module.instellar_link_deneb_gsm.cluster_id
  ]
  credential = {
    host     = module.aws_database_deneb_ayk.address
    password = module.aws_database_deneb_ayk.password
    port     = module.aws_database_deneb_ayk.port
    resource = module.aws_database_deneb_ayk.db_name
    username = module.aws_database_deneb_ayk.username
    secure   = true
  }

  driver                = "database/postgresql"
  driver_version        = module.aws_database_deneb_ayk.engine_version
  insterra_component_id = 201
  provider_name         = "aws"
  slug                  = module.aws_database_deneb_ayk.identifier
}
